### ISSUE TITLE
question on last commit

### ISSUE THREAD

**Issue by atom2ueki** [Qwikly/react-native-router-redux#5]
@malkomalko May I know why change the order for the view?

![screen shot 2015-11-27 at 5 44 41 pm](https://cloud.githubusercontent.com/assets/5100535/11438261/a6f29d96-952e-11e5-89d6-4c5e04977a51.png)

**Comment by malkomalko** [comment]
@atom2ueki With the navBar on top, it wasn't able to receive touches if the child was full screen since it would be rendered on top of the navBar.  The navbar is always pinned to the top (or should be) so this allows for it to appear in the correct location, and allow for it to receive touches.

Does this make sense?

**Comment by atom2ueki** [comment]
@malkomalko after having a test, if I put navBar under child, it will render like this

![screen shot 2015-11-28 at 10 42 05 am](https://cloud.githubusercontent.com/assets/5100535/11449758/db8fbc76-95bc-11e5-8d5a-a51812dbae47.png)

which is mean navBar is not always render on top

for the touches, does is related rendering arrangement ? 
https://github.com/facebook/react-native/issues/559

**Comment by malkomalko** [comment]
@atom2ueki can you show me a gist of the code you are using when trying to render the navbar?  If you are using a custom navbar instead of the included one from the examples, just make sure you 'position: absolute; top: 0'.  As for rendering arrangement, I don't believe there is a z-index yet, but I'll look into it.

**Comment by atom2ueki** [comment]
@malkomalko actually I'm  using the original sample file of what you provided, please have a look, thank you
https://gist.github.com/atom2ueki/107444dd76dff8199ccb

**Comment by malkomalko** [comment]
@atom2ueki I can replicate, I will provide a fix shortly.

**Comment by brunoksato** [comment]
I had the same bug here

**Comment by malkomalko** [comment]
I updated the example code: https://github.com/Qwikly/react-native-router-redux/commit/0d4e70f52278f5a56dd823ce132352639ae030f9 Basically, your main container has to be absolute.  This allows it to take up the whole space and scroll under the nav/tab bar.  Let me know if that works after updating the example.

**Comment by brunoksato** [comment]
not is better solution because repeat code all pages and need add top: 65, because is height navbar, but work

**Comment by malkomalko** [comment]
The other option is to put it back the way we had it, and rely on flex.  Then things will be spaced properly but scrolling will not happen under navbar.  Perhaps this is a better general solution?

**Comment by brunoksato** [comment]
yes I use this way and maybe is better solution for now

**Comment by atom2ueki** [comment]
@malkomalko your Qwikly project is awesome, just pledge it, waiting for it :+1:

**Comment by malkomalko** [comment]
I've set it up to give user's the choice via a layout property.  See https://github.com/Qwikly/react-native-router-redux/commit/7be577d5d2ca3cd288dd202c4cbd32396578b1bf.  This defaults to flex.
