### ISSUE TITLE
Access click event navbar in other components

### ISSUE THREAD

**Issue by brunoksato** [Qwikly/react-native-router-redux#6]
how can I access?

**Comment by malkomalko** [comment]
@brunoksato look at the NavBar.js file.  If you are using the provided NavBar you can pass in various props to your routes.  Of note to you, navLeftHandler and navRightHandler are functions that can be passed down.  Is this what you are looking for?

**Comment by brunoksato** [comment]
yes, how to access rightButton in other components, i have problem with this, may be some mistake my

**Comment by malkomalko** [comment]
Since this is hooked in to redux, you should pass a custom action in to your current routes navRightHandler prop and then respond accordingly in your component.  Does this make sense?  Perhaps if you give me an example of what you want to do, I can try throwing something together over the next few days for you.

**Comment by malkomalko** [comment]
closing for now, reopen if you are still having problems
